author: Zraphy

main: com.celestia.veo.Main
version: 1.0.0
name: Celestia
#api-version: 1.19.2

commands:
  zwp:
    aliases: ['worldprotect', 'zworldprotect']
    description: ZWorldProtect module command.
  chat:
    aliases: []
    description: ZChatManager module command.
  block:
    aliases: []
    description: ZChatManager module command.
  unblock:
    aliases: []
    description: ZChatManager module command.
  gen:
    aliases: ['generator']
    description: Celestia command.